<a href="https://colab.research.google.com/github/diosamuel/checkin-spatial-analysis/blob/main/TubesVDI.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import pandas as pd

In [2]:
NYC = pd.read_csv("https://raw.githubusercontent.com/diosamuel/checkin-spatial-analysis/refs/heads/main/dataset/dataset_TSMC2014_NYC.csv")
TKY = pd.read_csv("https://raw.githubusercontent.com/diosamuel/checkin-spatial-analysis/refs/heads/main/dataset/dataset_TSMC2014_TKY.csv")

# EDA

## Cek Missing Value

In [3]:
print("NYC")
print(NYC.isnull().sum())
print("TKY")
print(TKY.isnull().sum())

NYC
userId             0
venueId            0
venueCategoryId    0
venueCategory      0
latitude           0
longitude          0
timezoneOffset     0
utcTimestamp       0
dtype: int64
TKY
userId             0
venueId            0
venueCategoryId    0
venueCategory      0
latitude           0
longitude          0
timezoneOffset     0
utcTimestamp       0
dtype: int64

## Ubah VenueID ke nama tempat butuh api dari Foursquare

dikasih \$200 dollar tiap bulan

sekali hit api = $000.01 dollar

In [7]:
# Use boolean indexing for efficient search
matching_rows = NYC[NYC["venueId"] == "42911d00f964a520f5231fe3"]

# Access the results
matching_rows['Days'] = pd.to_datetime(matching_rows['utcTimestamp']).dt.day_name()

matching_rows["Days"].value_counts()

<ipython-input-7-eada76bee5eb>:5: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  matching_rows['Days'] = pd.to_datetime(matching_rows['utcTimestamp']).dt.day_name()
<ipython-input-7-eada76bee5eb>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  matching_rows['Days'] = pd.to_datetime(matching_rows['utcTimestamp']).dt.day_name()

Days
Friday       219
Tuesday      163
Saturday     162
Thursday     159
Wednesday    157
Monday       152
Sunday       135
Name: count, dtype: int64

In [ ]:
# Display all rows of the value counts
pd.set_option("display.max_rows", None)
# print(NYC["venueId"].value_counts())

In [ ]:
# Display all rows of the value counts
pd.set_option("display.max_rows", None)
# print(TKY["venueCategory"].value_counts())

#write to csv
TKY["venueCategory"].value_counts().to_csv("venueCategory.csv")
#write to excel
TKY["venueCategory"].value_counts().to_excel("venueCategory.xlsx")

In [ ]:
NYC.iloc[1]

userId                                        979
venueId                  4a43c0aef964a520c6a61fe3
venueCategoryId          4bf58dd8d48988d1df941735
venueCategory                              Bridge
latitude                                  40.6068
longitude                               -74.04417
timezoneOffset                               -240
utcTimestamp       Tue Apr 03 18:00:25 +0000 2012
Name: 1, dtype: object

In [ ]:
import requests
venueId = input('VenueID ')
versioning = "%2020231010"
oauth_token = "URKT0K1X0DOFMRKYKKYVVPGI1GIWVBRFCTP005RJFH1JKS0C"
url = f"https://api.foursquare.com/v2/venues/{venueId}/?v={versioning}&oauth_token={oauth_token}"

headers = {"accept": "application/json"}

response = requests.get(url, headers=headers)

print(response.text)

VenueID 42911d00f964a520f5231fe3
{"meta":{"code":200,"requestId":"6745cb01d74f44043608db56"},"notifications":[{"type":"notificationTray","item":{"unreadCount":0}}],"response":{"venue":{"id":"42911d00f964a520f5231fe3","name":"New York Penn Station","contact":{"phone":"2126306401","formattedPhone":"(212) 630-6401"},"location":{"address":"1 Penn Plz","crossStreet":"btwn W 31st & W 33rd St","lat":40.7501992792495,"lng":-73.99274826049805,"labeledLatLngs":[{"label":"display","lat":40.7501992792495,"lng":-73.99274826049805}],"radius50":119,"radius90":1631,"postalCode":"10001","cc":"US","neighborhood":"Chelsea","city":"New York","state":"NY","country":"United States","formattedAddress":["1 Penn Plz (btwn W 31st & W 33rd St)","New York, NY 10001","United States"]},"canonicalUrl":"https:\/\/foursquare.com\/newyorkp5446819","categories":[{"id":"4bf58dd8d48988d129951735","name":"Rail Station","pluralName":"Rail Stations","shortName":"Rail Station","icon":{"prefix":"https:\/\/ss3.4sqi.net\/img\/categories_v2\/travel\/trainstation_","suffix":".png"},"categoryCode":19047,"mapIcon":"fsq-default","primary":true}],"verified":true,"stats":{"tipCount":1672},"url":"https:\/\/www.amtrak.com\/stations\/nyp","likes":{"count":3300,"groups":[{"type":"others","count":3300,"items":[]}],"summary":"3300 Likes"},"like":false,"dislike":false,"ok":false,"header":"According to the Foursquare community, this place is a 5.7 out of 10.","rating":5.7,"ratingColor":"FF9600","ratingSignals":7544,"explanation":"We take into account visits and input from our community. You'll see a number on places based off of ratings and tips written by people like you.","ratingCategory":"poor","deliveryProviders":[{"id":"3310158","url":"https:\/\/www.seamless.com\/menu\/the-acai-station-338-8th-ave-new-york\/3310158?affiliate=1131&utm_source=foursquare-affiliate-network&utm_medium=affiliate&utm_campaign=1131&utm_content=3310158","provider":{"name":"seamless","icon":{"prefix":"https:\/\/fastly.4sqi.net\/img\/general\/cap\/","sizes":[40,50],"name":"\/delivery_provider_seamless_20180129.png"}}}],"beenHere":{"count":0,"unconfirmedCount":0,"marked":false,"lastCheckinExpiredAt":0},"photos":{"count":10904,"groups":[{"type":"venue","name":"Venue photos","count":10904,"items":[{"id":"518c3998498ed8cb973c65ae","createdAt":1368144280,"source":{"name":"Foursquare for iOS","url":"https:\/\/foursquare.com\/download\/#\/iphone"},"prefix":"https:\/\/fastly.4sqi.net\/img\/general\/","suffix":"\/186827_cLFraUIjzEr6ChGG_Sr8PI7od4RAOQXyOz6A6RS74qw.jpg","width":1920,"height":1440,"user":{"id":"186827","firstName":"Won Sun","lastName":"Parque","handle":"wonsunp7038616","privateProfile":false,"gender":"male","address":"","city":"","state":"","followingRelationship":"none","photo":{"prefix":"https:\/\/fastly.4sqi.net\/img\/user\/","suffix":"\/186827-DTXC4YFNNIDYQC3V.jpg"}},"visibility":"public"},{"id":"51de9477498ea0baa07914ea","createdAt":1373541495,"source":{"name":"Foursquare for iOS","url":"https:\/\/foursquare.com\/download\/#\/iphone"},"prefix":"https:\/\/fastly.4sqi.net\/img\/general\/","suffix":"\/4520788_pu9-XOE9fTEAmS1eg0uV652EsuJVH4wphly6ldx1-i0.jpg","width":1920,"height":1440,"user":{"id":"4520788","firstName":"Sahil","lastName":"Jain","handle":"sahilio","privateProfile":false,"gender":"male","countryCode":"US","followingRelationship":"none","photo":{"prefix":"https:\/\/fastly.4sqi.net\/img\/user\/","suffix":"\/D1KW5NVN5ATZCIYY.jpg"}},"visibility":"public"},{"id":"518fae07498e6b6a8bf8cfe4","createdAt":1368370695,"source":{"name":"Foursquare for iOS","url":"https:\/\/foursquare.com\/download\/#\/iphone"},"prefix":"https:\/\/fastly.4sqi.net\/img\/general\/","suffix":"\/772811_L-ZHUyrd9pBJ_vcHLA2Bv9Pi8gupSKhENRTGydEyHIM.jpg","width":1918,"height":1434,"user":{"id":"772811","firstName":"Darren","lastName":"Woolley","handle":"darrenp3","privateProfile":false,"gender":"male","address":"","city":"","state":"","followingRelationship":"none","photo":{"prefix":"https:\/\/fastly.4sqi.net\/img\/user\/","suffix":"\/RDHR3IJ3L3FFMECT.jpg"}},"visibility":"public"},{"id":"519151e4498e971bead5b8e7","createdAt":1368478180,"source":{"name":"Foursquare for iOS","url":"https:\/\/foursquare.com\/download\/#\/iphone"},"prefix":"https:\/\/fastly.4sqi.net\/img\/general\/","suffix":"\/25856439_sUc-4zJZeH9CZS5nnilqv8rWYGdALqSkoFt4zCzAaYQ.jpg","width":1440,"height":1920,"user":{"id":"25856439","firstName":"Cece","handle":"cece_stsucker","privateProfile":false,"gender":"female","countryCode":"US","followingRelationship":"none","photo":{"prefix":"https:\/\/fastly.4sqi.net\/img\/user\/","suffix":"\/25856439-3O3XFVDGIKSV3UU0.jpg"}},"visibility":"public"}]}]},"venuePage":{"id":"85006792"},"reasons":{"count":1,"items":[{"summary":"Lots of people like this place","type":"general","reasonName":"rawLikesReason"}]},"description":"Penn Station is the major intercity train station and a major commuter rail hub in New York City. Serving 300,000 passengers a day at a rate of up to a thousand every 90 seconds, it is the busiest passenger transportation facility in the United States and by far the busiest train station in North America.","storeId":"1214","page":{"user":{"id":"85006792","firstName":"New York Penn Station","handle":"newyorkp5446819","privateProfile":false,"gender":"none","countryCode":"US","followingRelationship":"none","photo":{"prefix":"https:\/\/fastly.4sqi.net\/img\/user\/","suffix":"\/85006792-Q5WEOPTXLUJSKMXV.png"},"type":"venuePage","venue":{"id":"42911d00f964a520f5231fe3"},"tips":{"count":0},"lists":{"groups":[{"type":"created","count":2,"items":[]}]},"homeCity":"New York, NY","bio":"","contact":{}}},"createdAt":1116806400,"hereNow":{"count":5,"summary":"5 people are here","groups":[{"type":"others","name":"Other people here","count":5,"items":[]}]},"tips":{"count":1672,"groups":[{"type":"self","name":"Tips you\u2019ve left here","count":0,"items":[]},{"type":"friends","name":"Tips from friends","count":0,"items":[]},{"type":"following","name":"Tips from people you follow","count":0,"items":[]},{"type":"others","name":"All tips","count":1672,"items":[{"id":"4ba93c3470c603bb047795b4","createdAt":1269382196,"text":"Stay to the right while standing on escalators to let people pass on the left","type":"user","canonicalUrl":"https:\/\/foursquare.com\/item\/4ba93c3470c603bb047795b4","likes":{"count":800,"groups":[{"type":"others","count":800,"items":[]}],"summary":"800 likes"},"like":false,"logView":true,"agreeCount":195,"disagreeCount":0,"todo":{"count":8},"user":{"id":"510780","firstName":"Chris","lastName":"Kramer","handle":"chrismkramer","privateProfile":false,"gender":"male","countryCode":"US","followingRelationship":"none","photo":{"prefix":"https:\/\/fastly.4sqi.net\/img\/user\/","suffix":"\/YVAR2S5RXRGX2IFP.jpg"}}},{"id":"4cbdfbb2ee00952152c5fb24","createdAt":1287519154,"text":"\u201cAt the moment of marching across Penn Station, there seemed to be mighty few travellers who would take sides for or against her.\u201d \u2014John O\u2019Hara, \u201cDrawing Room B\u201d","type":"user","url":"http:\/\/www.newyorker.com\/archive\/1947\/04\/19\/1947_04_19_025_TNY_CARDS_000208643","canonicalUrl":"https:\/\/foursquare.com\/item\/4cbdfbb2ee00952152c5fb24","likes":{"count":508,"groups":[{"type":"others","count":508,"items":[]}],"summary":"508 likes"},"like":false,"logView":true,"agreeCount":59,"disagreeCount":1,"todo":{"count":46},"user":{"id":"2611536","firstName":"The New Yorker","handle":"newyorker","privateProfile":false,"gender":"none","countryCode":"US","followingRelationship":"none","photo":{"prefix":"https:\/\/fastly.4sqi.net\/img\/user\/","suffix":"\/2611536-ZWKHMEGCZWBA3QQY.png"},"type":"page"}},{"id":"4c2cd11d8ef52d7f6a8033ba","createdAt":1278005533,"text":"Great place if you want to catch a train.","type":"user","canonicalUrl":"https:\/\/foursquare.com\/item\/4c2cd11d8ef52d7f6a8033ba","likes":{"count":354,"groups":[{"type":"others","count":354,"items":[]}],"summary":"354 likes"},"like":false,"logView":true,"agreeCount":74,"disagreeCount":0,"todo":{"count":4},"user":{"id":"618920","firstName":"Chris","lastName":"Ryan","handle":"chrisr2207514","privateProfile":false,"gender":"male","countryCode":"US","followingRelationship":"none","photo":{"prefix":"https:\/\/fastly.4sqi.net\/img\/user\/","suffix":"\/L0B5KDRZU0RBKXKV.jpg"}}},{"id":"4c695442d7b7ef3b4269c55d","createdAt":1281971266,"text":"The lost and found in this once glorious transit hub took in more than fifteen hundred umbrellas in 1947, according to a Talk of the Town story.","type":"user","url":"http:\/\/tny.com\/bQb2RV","canonicalUrl":"https:\/\/foursquare.com\/item\/4c695442d7b7ef3b4269c55d","likes":{"count":224,"groups":[{"type":"others","count":224,"items":[]}],"summary":"224 likes"},"like":false,"logView":true,"agreeCount":213,"disagreeCount":0,"todo":{"count":104},"user":{"id":"2611536","firstName":"The New Yorker","handle":"newyorker","privateProfile":false,"gender":"none","countryCode":"US","followingRelationship":"none","photo":{"prefix":"https:\/\/fastly.4sqi.net\/img\/user\/","suffix":"\/2611536-ZWKHMEGCZWBA3QQY.png"},"type":"page"}}]}]},"shortUrl":"http:\/\/4sq.com\/1GoinW","timeZone":"America\/New_York","listed":{"count":1320,"groups":[{"type":"others","name":"Lists from other people","count":1320,"items":[{"id":"4e4eb9cd483bb77049057415","name":"New York City Landmarks","description":"From skyscrapers to suspension bridges, visit check in here to for historic photos of New York's most famous spots like you've never seen them.","type":"others","user":{"id":"1241858","firstName":"The New York Daily News","handle":"nydailynews","privateProfile":false,"gender":"none","countryCode":"US","followingRelationship":"none","photo":{"prefix":"https:\/\/fastly.4sqi.net\/img\/user\/","suffix":"\/3EV01452MGIUWBAQ.jpg"},"type":"page"},"editable":false,"public":true,"collaborative":false,"url":"\/nydailynews\/list\/new-york-city-landmarks","canonicalUrl":"https:\/\/foursquare.com\/nydailynews\/list\/new-york-city-landmarks","createdAt":1313782221,"updatedAt":1405619156,"logView":true,"followers":{"count":601},"listItems":{"count":34,"items":[{"id":"t4cc1e8cc7ed8ef3b9bf011a0","createdAt":1313782221,"tip":{"id":"4cc1e8cc7ed8ef3b9bf011a0","createdAt":1287776460,"text":"PHOTO: Remember the old Penn Station? Click \"More Info\" to view travelers waiting for trains in 1942.","type":"user","url":"http:\/\/www.nydailynewspix.com\/sales\/largeview.php?name=5wj00kch.jpg&id=68639&lbx=-1&return_page=searchResults.php&searchDisplay=S&searchAction=advSearch&numFields=1&searchVal=Penn%20Station&Button=1&start=-2713888800&end=1287774162&dayFrom=1&monthFrom=1&y","canonicalUrl":"https:\/\/foursquare.com\/item\/4cc1e8cc7ed8ef3b9bf011a0","likes":{"count":51,"groups":[{"type":"others","count":51,"items":[]}],"summary":"51 likes"},"like":false,"logView":true,"agreeCount":50,"disagreeCount":0,"todo":{"count":62},"saves":{},"user":{"id":"1241858","firstName":"The New York Daily News","handle":"nydailynews","privateProfile":false,"gender":"none","countryCode":"US","followingRelationship":"none","photo":{"prefix":"https:\/\/fastly.4sqi.net\/img\/user\/","suffix":"\/3EV01452MGIUWBAQ.jpg"},"type":"page"}}}]}},{"id":"4e528c3c18381362f73026eb","name":"New York City","description":"Prêt à croquer la Grosse Pomme?","type":"others","user":{"id":"6082867","firstName":"ParisianGeek","handle":"parisiangeek","privateProfile":false,"gender":"none","countryCode":"FR","followingRelationship":"none","photo":{"prefix":"https:\/\/fastly.4sqi.net\/img\/user\/","suffix":"\/6082867-YRA5X0IQ1FO5OJA2.png"},"type":"page"},"editable":false,"public":true,"collaborative":false,"url":"\/parisiangeek\/list\/new-york-city","canonicalUrl":"https:\/\/foursquare.com\/parisiangeek\/list\/new-york-city","createdAt":1314032700,"updatedAt":1432916683,"photo":{"id":"523389c911d2db109c49c4ab","createdAt":1379109321,"prefix":"https:\/\/fastly.4sqi.net\/img\/general\/","suffix":"\/256867_CIu5FhyHmuNdnJ3TRW-OMt3fy62Q8yjrzN-fNVFCqjw.jpg","width":960,"height":641,"user":{"id":"256867","firstName":"Mike","handle":"mikaeldorian","privateProfile":false,"gender":"male","address":"","city":"","state":"","countryCode":"FR","followingRelationship":"none","photo":{"prefix":"https:\/\/fastly.4sqi.net\/img\/user\/","suffix":"\/256867_rwbT07Vb_sIpr85kUnT_RlBJETLOb4p9KZIFAfqXFuPrrQHmnYO_UzQHcvlBZV_-yj_G94shM"}},"visibility":"public"},"logView":true,"followers":{"count":598},"listItems":{"count":199,"items":[{"id":"v42911d00f964a520f5231fe3","createdAt":1326513689,"photo":{"id":"52235e8311d2bc86ac0619ef","createdAt":1378049667,"prefix":"https:\/\/fastly.4sqi.net\/img\/general\/","suffix":"\/54143895_CBC2xM-FUtSy4-nS_Y8G0DMlQzUOLVaWUcNMAtxt82Y.jpg","width":720,"height":960,"user":{"id":"54143895","firstName":"Taiki","lastName":"Yoshii","handle":"go_taiki441","privateProfile":false,"gender":"male","countryCode":"JP","followingRelationship":"none","photo":{"prefix":"https:\/\/fastly.4sqi.net\/img\/user\/","suffix":"\/AN3JUGBLSGEER0CH.jpg"}},"visibility":"public"}}]}}]}]},"phrases":[{"phrase":"amtrak","sample":{"entities":[{"indices":[0,6],"type":"keyPhrase"}],"text":"Amtrak to Albany or other upstate destinations?..."},"count":104},{"phrase":"lirr","sample":{"entities":[{"indices":[25,29],"type":"keyPhrase"}],"text":"... for your tickets the Lirr is packed starting at 7:30am."},"count":79},{"phrase":"train","sample":{"entities":[{"indices":[24,29],"type":"keyPhrase"}],"text":"... info window of your train's track assignment before it goes on the..."},"count":285}],"hours":{"status":"Open","richStatus":{"entities":[],"text":"Open"},"isOpen":true,"isLocalHoliday":false,"dayData":[],"timeframes":[{"days":"Mon\u2013Sun","includesToday":true,"open":[{"renderedTime":"24 Hours"}],"segments":[]}]},"popular":{"status":"Likely open","richStatus":{"entities":[],"text":"Likely open"},"isOpen":true,"isLocalHoliday":false,"timeframes":[{"days":"Today","includesToday":true,"open":[{"renderedTime":"7:00 AM\u201310:00 AM"},{"renderedTime":"4:00 PM\u20138:00 PM"}],"segments":[]},{"days":"Wed","open":[{"renderedTime":"7:00 AM\u201310:00 AM"},{"renderedTime":"4:00 PM\u20138:00 PM"}],"segments":[]},{"days":"Thu","open":[{"renderedTime":"7:00 AM\u201311:00 AM"},{"renderedTime":"3:00 PM\u20138:00 PM"}],"segments":[]},{"days":"Fri","open":[{"renderedTime":"7:00 AM\u20139:00 PM"}],"segments":[]},{"days":"Sat","open":[{"renderedTime":"9:00 AM\u20137:00 PM"}],"segments":[]},{"days":"Sun","open":[{"renderedTime":"10:00 AM\u20138:00 PM"}],"segments":[]},{"days":"Mon","open":[{"renderedTime":"7:00 AM\u201310:00 AM"},{"renderedTime":"4:00 PM\u20138:00 PM"}],"segments":[]}]},"seasonalHours":[],"defaultHours":{"status":"Open","richStatus":{"entities":[],"text":"Open"},"isOpen":true,"isLocalHoliday":false,"dayData":[],"timeframes":[{"days":"Mon\u2013Sun","includesToday":true,"open":[{"renderedTime":"24 Hours"}],"segments":[]}]},"pageUpdates":{"count":0},"inbox":{"count":0,"items":[]},"attributes":{"groups":[{"type":"payments","name":"Credit Cards","summary":"Credit Cards","count":7,"items":[{"displayName":"Credit Cards","displayValue":"Yes (incl. Discover & Visa)"}]},{"type":"wifi","name":"Wi-Fi","summary":"Wi-Fi","count":1,"items":[{"displayName":"Wi-Fi","displayValue":"Yes"}]},{"type":"touchTunes","name":"TouchTunes Jukebox","summary":"Yes","count":1,"items":[{"displayName":"No","displayValue":"Yes"}]}]},"bestPhoto":{"id":"518c3998498ed8cb973c65ae","createdAt":1368144280,"source":{"name":"Foursquare for iOS","url":"https:\/\/foursquare.com\/download\/#\/iphone"},"prefix":"https:\/\/fastly.4sqi.net\/img\/general\/","suffix":"\/186827_cLFraUIjzEr6ChGG_Sr8PI7od4RAOQXyOz6A6RS74qw.jpg","width":1920,"height":1440,"visibility":"public"}}}}

In [ ]:
import json
print(json.dumps(json.loads(response.text), indent=2))

In [ ]:
NYC_userid_counts = NYC['userId'].value_counts()
NYC_userid_counts.head(5)

userId
293    2697
185    2079
354    2061
315    1682
84     1376
Name: count, dtype: int64

# Ambil Nama by UserID

In [ ]:
from bs4 import BeautifulSoup
API_PATH = f"http://foursquare.com/user/979"
response = requests.get(API_PATH)

soup = BeautifulSoup(response.text, 'html.parser')
name_element = soup.find(class_="name")
if name_element:
    name = name_element.text
    print(name)

Ilkka Järstä

1. Dimana saja tempat yang sering dikunjungi di kota New York dan Tokyo?
[visualisasi peta] ahmet
2. Pada waktu kapan saja tempat atau area tersebut mulai sibuk?
[kalau per hari - visualisasi barplot]
3. Dalam hitungan per waktu, kategori tempat apa yang orang sering kunjungi?(per hari, per bulan, per minggu, dll)
[visualisasi barplot]
4. Apakah ada hubungan antara lokasi geografis dengan frekuensi kunjungan masyarakat? [visualisasi heatmap]
5. Bagaimana perbedaan waktu kunjungan pada kategori tempat yg sama di kedua kota?  (spend time, atau pagi/siang/malam antara kedua tempat tsb) [barplot]


kategori yg bisa dianalisis
1. Tempat Makan/Restoran
2. Transportasi Umum
3. Wisata
4. Belanja (Entertainment)
5. Public Service & Area
6. Residental (Home & Neighborhood)
5. Working Place

# Merging
membuat kategori global dari sub-kategori

adakalanya tiap daerah (Tokyo dan New York City) mempunyai venueCategory yang berbeda dan unik, maka diperlukan untuk membuat kolom kategori global untuk menyamaratakan antar kota

In [91]:
TKYcat = pd.read_csv("https://raw.githubusercontent.com/diosamuel/checkin-spatial-analysis/refs/heads/main/dataset/TKYcat.csv")
NYCcat = pd.read_csv("https://raw.githubusercontent.com/diosamuel/checkin-spatial-analysis/refs/heads/main/dataset/NYCcat.csv")

In [92]:
TKYcat.sample(3)

          venueCategory  count           Kategori
239  Mac & Cheese Joint      2       Tempat Makan
165     Harbor / Marina     76  Transportasi Umum
223                City      7     Layanan Publik

In [90]:
NYCcat.sample(3)

            venueCategory  count           Kategori
106             Pet Store    302     Layanan Publik
218          Antique Shop     27  Belanja & Hiburan
202  Malaysian Restaurant     43       Tempat Makan

merge NYC

In [86]:
merged_df = pd.merge(NYCcat, NYC, on="venueCategory", how="inner")
merged_df.sample(10)

,venueCategory,count,Kategori,userId,venueId,venueCategoryId,latitude,longitude,timezoneOffset,utcTimestamp
217133,Toy / Game Store,229,Belanja & Hiburan,559,4283ee00f964a520ce221fe3,4bf58dd8d48988d1f3941735,40.763556,-73.972868,-240,Sun Apr 15 15:49:11 +0000 2012
175006,Church,1172,Layanan Publik,545,4cc4745e42d1b60c61bb1d13,4bf58dd8d48988d132941735,40.678716,-73.922582,-240,Wed Sep 05 13:41:07 +0000 2012
102875,Residential Building (Apartment / Condo),4185,Residental (Perumahan/Privat),664,4fbd9dbbe4b0059acac76ef8,4d954b06a243a5684965b473,40.637151,-73.967366,-240,Sun Jun 10 09:28:38 +0000 2012
138222,Pizza Place,2469,Tempat Makan,316,4d41f0b4aed776eb54a06997,4bf58dd8d48988d1ca941735,40.665797,-74.234643,-240,Fri Apr 20 17:04:15 +0000 2012
154518,Fast Food Restaurant,1600,Tempat Makan,422,4c82c3ee51ada1cd6fff1f10,4bf58dd8d48988d16e941735,40.728492,-74.218004,-240,Tue May 29 23:21:36 +0000 2012
123965,Road,3207,Layanan Publik,267,4e88e564b803b97a0afa57e6,4bf58dd8d48988d1f9931735,40.823250,-73.886409,-240,Sun Apr 22 01:00:04 +0000 2012
98473,Deli / Bodega,4214,Tempat Makan,1031,4b5dd227f964a520a76d29e3,4bf58dd8d48988d146941735,40.755070,-73.973559,-240,Fri May 25 17:08:08 +0000 2012
77548,Train Station,6408,Transportasi Umum,473,4eeaa4ed77c8730d38061384,4bf58dd8d48988d129951735,40.858619,-73.855825,-240,Fri Apr 20 12:44:44 +0000 2012
113741,College Academic Building,3479,Layanan Publik,992,4c2cbe668ef52d7fdc5b33ba,4bf58dd8d48988d198941735,40.636492,-74.025493,-240,Thu Apr 19 13:33:52 +0000 2012
167141,Music Venue,1424,Layanan Publik,518,46be68fef964a520e2491fe3,4bf58dd8d48988d1e5931735,40.743037,-74.005731,-240,Sun Aug 19 01:16:37 +0000 2012

In [82]:
merged_df.to_csv("NYC_final.csv")

merge TKY

In [87]:
merged_df = pd.merge(TKYcat, TKY, on="venueCategory", how="inner")
merged_df.sample(10)

,venueCategory,count,Kategori,userId,venueId,venueCategoryId,latitude,longitude,timezoneOffset,utcTimestamp
162907,Train Station,200428,Transportasi Umum,1157,4cf5064b7e93f04dc6666069,4bf58dd8d48988d129951735,35.728372,139.711123,540,Sat Dec 15 04:26:32 +0000 2012
125830,Train Station,200428,Transportasi Umum,2203,4b5c0445f964a520502129e3,4bf58dd8d48988d129951735,35.788274,139.612915,540,Wed Oct 24 20:02:53 +0000 2012
245351,Ramen / Noodle House,17303,Tempat Makan,112,4e83f44b9adfdb604fcb360c,4bf58dd8d48988d1d1941735,35.694978,139.766558,540,Fri May 11 12:23:16 +0000 2012
152751,Train Station,200428,Transportasi Umum,1524,4b23d1faf964a5206c5a24e3,4bf58dd8d48988d129951735,35.733457,139.739633,540,Sun Dec 02 05:15:10 +0000 2012
392276,Road,7528,Layanan Publik,1851,4b764146f964a52077452ee3,4bf58dd8d48988d1f9931735,35.702912,139.771687,540,Wed Jan 30 11:17:33 +0000 2013
497746,Event Space,2209,Layanan Publik,822,4ca8484097c8a1cd8f6383a5,4bf58dd8d48988d171941735,35.553168,139.729700,540,Tue Nov 20 10:27:51 +0000 2012
357225,Office,8789,Tempat Kerja,409,4bbac8b753649c742f7249fb,4bf58dd8d48988d125941735,35.699828,139.772359,540,Fri Oct 26 00:12:32 +0000 2012
278705,Japanese Restaurant,15680,Tempat Makan,113,4e290d52e4cd6c6cb34d84b4,4bf58dd8d48988d111941735,35.689004,139.697417,540,Fri May 04 22:58:08 +0000 2012
186914,Train Station,200428,Transportasi Umum,942,4b90c61ff964a520f99633e3,4bf58dd8d48988d129951735,35.730375,139.712405,540,Sat Jan 26 09:13:30 +0000 2013
116838,Train Station,200428,Transportasi Umum,1333,4b19f917f964a520abe623e3,4bf58dd8d48988d129951735,35.698596,139.773018,540,Thu Sep 13 10:20:19 +0000 2012

In [84]:
merged_df.to_csv("TKY_final.csv")